<?php

return [
    'keys' => [
        'nolf' => 'Jn3Ab4',
        'nolf2' => 'g3Fo6x',
        'warlordsb' => '9gV5Hm',
        'warlordsb2' => 'Gg7nLf',
        'warbatcry3' => 'b00p', // This one is amazingly generated by me
        'warlordsdr' => 'exS6aj', // Warlords 3
    ],
    // Currently supported games. Any attempt at creating games that aren't under this will fail!
    'supported_games' => [
        'nolf',
        'nolf2'
    ]
];
